export const SAVE_PALETTE = "SAVE_PALETTE";
export const TOGGLE_SWATCH = "TOGGLE_SWATCH";
export const SET_SWATCHES = "SET_SWATCHES";
export const CLEAR_CART = "CLEAR_CART";
export const DELETE_PALETTE = "DELETE_PALETTE";
